theme: jekyll-theme-minimal
title: Meg Graham MacLean, PhD
description: "Lecturer of Quantitative Ecology, Department of Environmental Conservation, University of Massachusetts - Amherst"
authors: Meg Graham MacLean
