theme = "soho"
baseurl = "https://github.com/meggmaclean/git-web-site.git"
languageCode = "en"
title = "Meg Graham MacLean"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]

[params]
title = "Meg Graham MacLean"
description = "Example Site"
gravatar = "mgmaclean@umass.edu"
images = ["images/profile.png"]
profilePicture = "images/profile.png"
copyright = "Meg Graham MacLean"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]


## Set custom theme color.
# themeColor = "#fc2803"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "#"
  
  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Publications"
  identifier = "pubs"
  weight = 20
  url = "/pubs/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4


